[package]
name = "zip"
version = "0.7.0-alpha1"
authors = ["Marli Frost <marli@frost.red"]
license = "UNLICENSE"
repository = "https://github.com/zip-rs/zip.git"
keywords = ["zip", "archive"]
description = """
A portable cross-platform archive format
"""
edition = "2018"

[dependencies]
